### ISSUE TITLE
Replace mirror.pkgbuild.com with geo.mirror.pkgbuild.com

### ISSUE THREAD

**Issue by nl6720** [jp112sdl/HMIPServer-Shell#1]
https://github.com/jp112sdl/HMIPServer-Shell/blob/a030a245afe75dedb17b07bbc3b97b94a93ece42/enableHMIPServerCommandShellRM.sh#L35-L46

mirror.pkgbuild.com is [not public](https://archlinux.org/mirrors/mirror.pkgbuild.com/). Using it generates excessive traffic to Arch's infrastructure.

Its replacement is [geo.mirror.pkgbuild.com](https://geo.mirror.pkgbuild.com/). See https://gitlab.archlinux.org/archlinux/infrastructure/-/merge_requests/522 for details.

**Comment by jp112sdl** [comment]
Thanks for the tip!
Done, [9b24f25](https://github.com/jp112sdl/HMIPServer-Shell/commit/9b24f25b93a9f0902f5f1e41e63dd789368bfd31)
